/**
 * Generated by orval v6.1.1 🍺
 * Do not edit manually.
 * Nightborn Dev Exercise API
 * Swagger for Nightborn-dev-exercise-back-end project.

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */

/**
 * Model base model definition, including fields `ID`, `CreatedAt`, `UpdatedAt`, `DeletedAt`, which could be embedded in your models
type User struct {
gorm.Model
}
 */
export interface Model {
  CreatedAt?: string;
  DeletedAt?: string;
  ID?: number;
  UpdatedAt?: string;
}
